# permissions for end users to view cilia.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ansible-operator-cilium
    app.kubernetes.io/managed-by: kustomize
  name: cilium-viewer-role
rules:
- apiGroups:
  - alvistack
  resources:
  - cilia
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alvistack
  resources:
  - cilia/status
  verbs:
  - get
