---
- name: Build kustomize testing overlay
  command: '{{ kustomize }} build --load-restrictor LoadRestrictionsNone'
  args:
    chdir: '{{ config_dir }}/testing'
  register: resources
  changed_when: false
- name: Set resources to {{ state }}
  k8s:
    definition: '{{ item }}'
    state: '{{ state }}'
    wait: false
  loop: '{{ resources.stdout | from_yaml_all | list }}'
- name: Wait for resources to get to {{ state }}
  k8s:
    definition: '{{ item }}'
    state: '{{ state }}'
    wait: true
  loop: '{{ resources.stdout | from_yaml_all | list }}'
